version: '2'
services:
  server:
    build: .
    ports:
      - ${PORT}:5000
    volumes:
      - $PWD:/work
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=server.py
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ["./wait-for-it.sh", "db:5432", "--", "gunicorn", "--workers=4", "--bind=0.0.0.0:5000", "server:app"]
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_volume:
